homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.6767438
  longitude: -81.41720740000001
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 218
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages
config:
conversation:
discovery:
frontend:
  themes: !include themes.yaml
# history:
http:
  # api_password: !secret http_api_key  
  ssl_certificate: /usr/local/etc/letsencrypt/live/deepthink.asuscomm.com/fullchain.pem
  ssl_key: /usr/local/etc/letsencrypt/live/deepthink.asuscomm.com/privkey.pem  
  base_url: "https://deepthink.asuscomm.com"
  trusted_networks: 
    - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
  # server_host: 192.168.1.15
logbook:
  include:
    domains:
      - automation
      - script
      - input_boolean
      - binary_sensor
    entities:
      - sensor.progressive_day_theme
      - sensor.time_of_day
      - device_tracker.lg_g7
      - group.nick
updater:
sun:
tts:
  platform: google
zeroconf:

intent_script: !include voice_intents.yaml

logger:
  default: warn
  logs:
    homeassistant.components.media_player: error
    homeassistant.components.script: debug
    # homeassistant.components.switch.command_line: debug

alexa:

amcrest:
  host: 192.168.1.180
  username: !secret amcrest_username
  password: !secret amcrest_password

asuswrt:
  host: 192.168.1.1
  username: !secret router_username
  password: !secret router_password
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

ecobee:
  api_key: !secret ecobee_api_key

binary_sensor:
  - platform: workday
    country: US
    province: OH
  - platform: rest
    resource: http://192.168.1.17/api/hUYgWbmGK7ozsgJ4HZrXQbF8-XQ3URytT7Zqx927/sensors/8
    value_template: '{{ value_json.state.status }}'
    scan_interval: 2
    name: 'Workshop Hue 1 Motion'
  - platform: template
    sensors: 
      motion:
        friendly_name: "Motion"
        value_template: >-
          {%- if is_state('binary_sensor.basement_bathroom_motion', 'on') 
            or is_state('binary_sensor.bedroom_motion', 'on') 
            or is_state('binary_sensor.kitchen_motion', 'on') 
            or is_state('binary_sensor.living_room_motion', 'on') 
            or is_state('binary_sensor.office_motion', 'on')
            or is_state('binary_sensor.master_bathroom_motion', 'on')
            or is_state('binary_sensor.sun_room_motion', 'on')  
            or is_state('binary_sensor.upstairs_motion_1_sensor', 'on')
            or is_state('binary_sensor.workshop_sensor', 'on')  
          -%}
          true
          {%- else -%}
          false
          {%- endif -%}
      basement_bathroom_motion:
        friendly_name: "Basement Bathroom Motion"
        value_template: >-
          {%- if is_state('sensor.basement_bathroom_motion_1_burglar', '8') -%}
          true
          {%- else -%}
          false
          {%- endif -%}          
      bedroom_motion:
        friendly_name: "Bedroom Motion"
        value_template: >-
          {%- if is_state('sensor.bedroom_motion_1_burglar', '8') -%}
          true
          {%- else -%}
          false
          {%- endif -%}
      living_room_motion:
        friendly_name: "Living Room Motion"
        value_template: >-
          {%- if is_state('sensor.living_room_motion_3_burglar', '8') 
            or is_state('binary_sensor.living_room_motion_1_sensor', 'on')
          -%}
          true
          {%- else -%}
          false
          {%- endif -%}          
      kitchen_motion:
        friendly_name: "Kitchen Motion"
        value_template: >-
          {%- if is_state('sensor.kitchen_motion_1_burglar', '8') -%}
          true
          {%- else -%}
          false
          {%- endif -%}
      office_motion:
        friendly_name: "Office Motion"
        value_template: >-
          {%- if is_state('sensor.office_motion_1_burglar', '8') -%}
          true
          {%- else -%}
          false
          {%- endif -%}    
      master_bathroom_motion:
        friendly_name: "Master Bathroom Motion"
        value_template: >-
          {%- if is_state('sensor.master_bathroom_motion_1_burglar', '8') -%}
          true
          {%- else -%}
          false
          {%- endif -%}            
      sun_room_motion:
        friendly_name: "Sun Room Motion"
        value_template: >-
          {%- if is_state('sensor.sun_room_motion_1_burglar', '8') 
            or is_state('binary_sensor.sun_room_motion_1_sensor_2', 'on')
          -%}
          true
          {%- else -%}
          false
          {%- endif -%}
      workshop_motion:
        friendly_name: "Workshop Motion"
        value_template: >-
          {%- if is_state('binary_sensor.workshop_hue_1_motion', 'on') -%}
          true
          {%- else -%}
          false
          {%- endif -%}
      bedroom_media_active:
        friendly_name: "Bedroom Media Active"
        value_template: >-
          {%- if is_state('media_player.bedroom_fire_stick', 'playing') 
            or is_state('media_player.bedroom_dot', 'playing') 
            or is_state('media_player.bedroom_tv', 'playing') 
          -%}
          true
          {%- else -%}
          false
          {%- endif -%}      
      living_room_media_active:
        friendly_name: "Living Room Media Active"
        value_template: >-
          {%- if is_state('media_player.living_room_cr2', 'playing') 
            or is_state('media_player.living_room_dot', 'playing') 
            or is_state('media_player.living_room_display', 'playing') 
            or is_state('media_player.living_room_stereo', 'playing') 
            or is_state('media_player.vizio_tv', 'playing')             
          -%}
          true
          {%- else -%}
          false
          {%- endif -%}
      masterbath_media_active:
        friendly_name: "Master Bath Media Active"
        value_template: >-
          {%- if is_state('media_player.bathroom_speaker', 'playing') 
          -%}
          true
          {%- else -%}
          false
          {%- endif -%}
      media_active:
        friendly_name: "Media Active"
        value_template: >-
          {%- if is_state('binary_sensor.living_room_media_active', 'on') 
            or is_state('binary_sensor.bedroom_media_active', 'on') 
          -%}
          true
          {%- else -%}
          false
          {%- endif -%}

cast:
  media_player: 
    - host: 192.168.1.210          
    - host: 192.168.1.223
    
emulated_hue:
  host_ip: 192.168.1.15
  exposed_domains:
    - group
    - input_boolean
    - switch
#    - light

envisalink:
  host: 192.168.1.25
  panel_type: HONEYWELL
  user_name: !secret envisa_username
  password: !secret envisa_password
  code: '2580'
  port: 4025
  evl_version: 4
  zones:
    9:
      name: 'Front Door'
      type: 'opening'
    10:
      name: 'Back Door'
      type: 'opening'
    11:
      name: 'Garage Door'
      type: 'opening'
    12:
      name: 'Living Room Motion 1 Sensor'
      type: 'motion'
    13:
      name: 'Sun Room Motion 1 Sensor'
      type: 'motion'
    14:
      name: 'Upstairs Motion 1 Sensor'
      type: 'motion'
  partitions:
    1:
      name: 'Home Alarm'

google_assistant:
  project_id: hass-deepthink
  api_key: !secret google_api_key
  exposed_domains:
    - group
    - input_boolean
    # - light
    - switch
    
    
  # entity_config:
  #   switch.kitchen:
  #     name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
  #     aliases:
  #       - BRIGHT_LIGHTS
  #       - ENTRY_LIGHTS
  #   light.living_room:
  #     expose: false
  #     room: LIVING_ROOM

hue:
  bridges:
    - host: 192.168.1.17
      allow_hue_groups: false

input_boolean:
  is_living_room_dim:
    name: "Active Living Room"
    initial: off
  sleep_mode:
    name: "Sleep Mode"
    initial: off
    icon: mdi:sleep
  debug_mode:
    name: "Debug Mode"
    initial: off
    icon: mdi:bug
  house_auto_lights:
    name: "House Auto Lights"
    initial: on
  tv_auto_lights:
    name: "Tv Auto Lights"
    initial: On
  guests_present:
    name: "Guests Present"
    initial: off
  auto_lights_climate:
    name: "Auto Lights Climate"
    initial: off
  state_climate_scene_active:
    name: "Climate Scene Actived"
    initial: off
  office_main_temp:
    name: "Office Temperature Watch"
    initial: off
  office_override:
    name: "Office Override"
    initial: off
  alarms_work_enabled:
    name: "Weekday Alarm Enabled"
    initial: on
  alarms_one_off_enabled:
    name: "One Off Alarm Enabled"
    initial: off
  random_color_mode:
    name: "Random Color Mode"
    initial: off
  occupancy:
    name: "Occupancy Detected"
    initial: off

input_datetime:
  alarms_work:
    name: "Work Alarm Time"
    has_date: false
    has_time: true
    initial: "07:00"
  alarms_one_off:
    name: "One Off Alarm Time"
    has_date: false
    has_time: true
    initial: "10:30"

lifx:
  light:
    server: 192.168.1.15
    
lovelace:
  mode: yaml

mqtt:
  broker: 192.168.1.7
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

octoprint:
  host: 192.168.1.35
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

influxdb:
  host: 192.168.1.13
  username: !secret influx_user
  password: !secret influx_password

recorder:
  purge_interval: 1
  purge_keep_days: 4

roku:
  - host: 192.168.1.71

shell_command: 
  renew_ssl: /usr/local/bin/certbot certonly renew
  # --standalone --preferred-challenges http-01 --email nsimone1911@gmail.com -d deepthink.asuscomm.com

system_health:

timer:
  randomize_color:
    duration: 300
# upnp:
#   port_mapping: false

# wink:
wemo:

zwave:
 usb_path: /dev/cuau1
 network_key: !secret zwave_network_key


#automation: !include automations.yaml
automation: !include_dir_list automations
device_tracker: !include_dir_list device_trackers
input_select: !include input_selects.yaml
input_number: !include input_number.yaml
group: !include groups.yaml
light: !include_dir_list lights
notify: !include_dir_list notify
media_player: !include_dir_list media_players
scene: !include_dir_list scenes
script: !include_dir_named scripts
sensor: !include_dir_list sensors
switch: !include_dir_list switches
