alias: 'Arrival'
trigger:
  # platform: state
  # entity_id: group.nick
  # to: 'home'
  - platform: state
    entity_id: input_boolean.occupany
    to: 'on'  
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
action:
  - service: light.turn_on
    entity_id: group.living_room_lights
  - service: light.turn_on
    entity_id: group.accents
  - service: climate.set_away_mode
    entity_id: climate.main_floor
    data:
      away_mode: 'off'
  - condition: state
    entity_id: script.progressive_theme
    state: 'off'
  - service: script.turn_on
    entity_id: script.progressive_theme