alias: 'Arrival Night'
trigger:
  # platform: state
  # entity_id: group.nick
  # to: 'home'
  platform: state
  entity_id: input_boolean.occupany
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: "-0:59:59"
action:    
  - service: light.turn_on
    entity_id: group.sun_room_lights
