alias: 'Arrival'
trigger:
  platform: state
  entity_id: group.nick
  to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - condition: sun
      before: sunset
      before_offset: "-1:00:00"
action:
  - service: light.turn_on
    entity_id: group.living_room_lights
  - service: light.turn_on
    entity_id: group.accents
  - service: climate.set_away_mode
    entity_id: climate.main_floor
    data:
      away_mode: 'off'
  # - service: notify.pushbullet
  #   data:
  #     title: Welcome Home
  #     message: Turning on accent lights
  - condition: state
    entity_id: script.progressive_theme
    state: 'off'
  - service: script.turn_on
    entity_id: script.progressive_theme