alias: 'Arrival'
trigger:
  platform: state
  entity_id: group.nick
  to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - condition: sun
      before: sunset
      before_offset: "-1:00:00"
action:
 - service: scene.turn_on
   entity_id: scene.living_room_warm
 - service: light.turn_on
   entity_id: light.office_b_1
 - service: light.turn_on
   entity_id: light.sun_room_b_1
 - service: light.turn_on
   entity_id: light.sun_room_b_2   
 - service: climate.set_away_mode
   entity_id: climate.main_floor
   data:
     away_mode: 'off'   
 - service: notify.pushbullet
   data:
     title: Welcome Home
     message: Turning on accent lights
#  - service: mqtt.publish
#    data:
#      topic: "hass/kitchen-leds-1/set-color"
#      data: "240,25,0"
#  - service: mqtt.publish
#    data: 
#      topic: "hass/kitchen-leds-1/set-effect"
#      payload: "Juggle"
#  - service: mqtt.publish
#    data:
#      topic: "hass/kitchen-leds-1/set-animation-speed"
#      payload: 5