alias: 'Auto On Lights Generic'
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bedroom_occupancy
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.office_occupancy
    to: 'on'       
  - platform: state
    entity_id: binary_sensor.sun_room_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.workshop_motion
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  # - condition: and
  #   conditions:
  #     - condition: template
  #       value_template: >-
  #         {% set fullNameParts = trigger.entity_id.split('.') %}
  #         {% set nameParts = fullNameParts[1].split('_') %}
  #         {% set roomName = 'binary_sensor.' + nameParts[0] %}
  #         {% if(nameParts[1] == 'room') %}
  #           {% set roomName = roomName + '_room' %}
  #         {% endif %}
  #         {% if( is_state(roomName + '_media_active', 'on') ) %}
  #           true
  #         {% else %}
  #           false
  #         {% endif %}
  - condition: template
    value_template: >-
      {% set fullNameParts = trigger.entity_id.split('.') %}
      {% set nameParts = fullNameParts[1].split('_') %}
      {% set roomName = 'binary_sensor.' + nameParts[0] %}      
      {% set sceneName = nameParts[0] %}
      {% if(nameParts[1] == 'room') %}
        {% set sceneName = sceneName + '_room' %}
        {% set roomName = roomName + '_room' %}
      {% endif %}
      {% if( is_state(roomName + '_media_active', 'on') ) %}
        {% set sceneName = sceneName + "_" +  states('sensor.progressive_day_theme') | replace(' ', '_') | lower  %}
        {% set foundDim = false %}
        {% for entity_id in states.scene[sceneName].attributes.entity_id -%}
          {% if (states(entity_id) == 'off' or state_attr(entity_id, 'brightness') | int < states('input_number.constant_brightness_dim') | int) %}
            {% set foundDim = true %}
          {% endif %}
        {% endfor%}
        {{ foundDim }}         
      {% else %}
        true
      {% endif %}       
action:
  - service: scene.turn_on
    data_template:
      entity_id: >-
        {% set fullNameParts = trigger.entity_id.split('.') %}
        {% set nameParts = fullNameParts[1].split('_') %}
        {% set sceneName = nameParts[0] %}
        {% if(nameParts[1] == 'room') %}
          {% set sceneName = sceneName + '_room' %}
        {% endif %}
        scene.{{ sceneName }}_{{ states('sensor.progressive_day_theme')|replace(' ', '_') | lower }}