alias: 'Auto Lights Living Room'
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
condition:
  - condition: state
    entity_id: group.living_room_lights
    state: 'off'
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  # - condition: template
  #   value_template: '{{ states("media_player.living_room_cr2") == "idle" }}'
action:
  - service: scene.turn_on
    data_template:
      entity_id:
        scene.living_room_{{ states('sensor.progressive_day_theme')|replace(' ', '_') | lower }}