alias: 'Auto Lights Bedroom'
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bedroom_occupancy
    to: 'on' 
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
action:
  - service: scene.turn_on
    data_template:
      entity_id:
        scene.bedroom_{{ states('sensor.progressive_day_theme')|replace(' ', '_') | lower }}
  # - service: script.auto_light_on
  #   data:
  #     entity: "light.bedroom_c_1"
  # - service: script.auto_light_on
  #   data:
  #     entity: "light.bedroom_c_2"
  # - service: script.auto_light_on
  #   data:
  #     entity: "light.bedroom_c_3"