alias: 'Auto Off Office'
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion_1_sensor
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.office_occupancy
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'    
action:
  - service: script.auto_light_off
    data:
      entity: light.office_c_1
  - service: script.auto_light_off
    data:
      entity: light.office_l_1
  - service: script.auto_light_off
    data:
      entity: light.office_b_1