alias: 'Auto Light Sun Room'
trigger:
  - platform: state
    entity_id: binary_sensor.sun_room_motion
    to: 'on'    
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
action:
  - service: scene.turn_on
    data_template:
      entity_id:
        scene.sun_room_{{ states('sensor.progressive_day_theme')|replace(' ', '_') | lower }}