alias: 'Auto Lights Kitchen'
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.kitchen_motion_1_luminance
    below: '30'
action:
  - service: scene.turn_on
    data_template:
      entity_id:
        scene.kitchen_{{ states('sensor.progressive_day_theme')|replace(' ', '_') | lower }}
  # - service: script.auto_light_on
  #   data:
  #     entity: "light.kitchen_d_1"
  # - service: script.auto_light_on
  #   data:
  #     entity: "light.kitchen_d_2"
  # - service: script.auto_light_on
  #   data:
  #     entity: "light.kithen_strip_1"
  #     effect: solid