alias: "Auto Night Light Office"
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion_1_sensor
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: group.office_lights
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
action:
  - service: scene.turn_on
    entity_id: scene.office_night_light
  # - service: notify.pushbullet
  #   data:
  #     title: Debugging Message
  #     message: Sun Room Night Light Triggered