alias: 'Auto Lights Bedroom'
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_motion_1_sensor
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bedroom_occupancy
    to: 'on' 
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
action:
  - service: script.auto_light_on
    data:
      entity: "light.bedroom_c_1"
  - service: script.auto_light_on
    data:
      entity: "light.bedroom_l_1"