alias: 'Auto Night Lights Kitchen'
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: group.kitchen_lights
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.kitchen_motion_1_luminance
    below: '1'
action:  
  - service: scene.turn_on
    entity_id: scene.kitchen_night_light