alias: 'Auto Night Lights Bedroom'
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_motion
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: group.bedroom_lights
    state: 'off'
  - condition: sun
    after: sunset
action:  
  - service: scene.turn_on
    entity_id: scene.bedroom_night_light