alias: 'Auto Lights Office'
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion_1_sensor
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.office_occupancy
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'    
action:
  - service: script.auto_light_on
    data:
      entity: "light.office_c_1"
  - service: script.auto_light_on
    data:
      entity: "light.office_l_1"
  - service: script.auto_light_on
    data:
      entity: "light.office_b_1"