alias: 'Auto Off Basement Bath'
trigger:
  - platform: state
    entity_id: binary_sensor.basement_bathroom_motion
    to: 'off'
    for:
      minutes: 20
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'    
action:
  - service: script.auto_light_off
    data:
      entity: group.basement_bathroom_lights