alias: 'Auto Off Master Bath'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.master_bathroom_motion
    to: 'off'
    for:
      minutes: 40
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  # - condition: state
  #   entity_id: input_boolean.sleep_mode
  #   state: 'off'
action:
  - service: script.auto_light_off
    data:
      entity: group.master_bathroom_lights