alias: 'Auto Off Bedroom'
trigger:
  platform: state
  entity_id: binary_sensor.bedroom_1_motion
  from: 'off'
  to: 'on'
  # for:
  #   minutes: 45
condition:
  # condition: or
  # conditions:
  #   - condition: state
  #     entity_id: binary_sensor.upstairs_motion
  #     state: 'on'
  - condition: state
    entity_id: binary_sensor.bedroom_1_motion
    state: 'off'
    for:
      minutes: 20
action:
  - service: light.turn_off
    entity_id: light.bedroom_c_1
  - service: light.turn_off
    entity_id: light.bedroom_l_1  