alias: 'Auto Off Office'
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion
    to: 'off'
    for:
      minutes: 40
  - platform: state
    entity_id: binary_sensor.office_occupancy
    to: 'off'
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.office_motion
        state: 'off'
      - condition: state
        entity_id: binary_sensor.office_occupancy
        state: 'off'
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'    
action:
  - service: script.auto_light_off
    data:
      entity: light.office_c_1
  - service: script.auto_light_off
    data:
      entity: light.office_l_1
  # - service: script.auto_light_off
  #   data:
  #     entity: light.office_b_1