alias: 'Auto Lights Kitchen'
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion_1_sensor
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'    
action:
  - service: script.auto_light_on
    data:
      entity: "light.kitchen_d_1"
  - service: script.auto_light_on
    data:
      entity: "light.kitchen_d_2"
  - service: script.auto_light_on
    data:
      entity: "light.kithen_strip_1"