alias: 'Auto Lights Basement Bath'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.basement_bathroom_motion
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
action:
  - service: script.auto_light_on
    data:
      entity: "group.basement_bathroom_lights"
      brightness: 255