alias: 'Auto Lights Living Room'
trigger:
  # - platform: state
  #   entity_id: binary_sensor.living_room_motion_1_sensor
  #   to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_occupancy
    to: 'on'
condition:
  - condition: state
    entity_id: group.living_room_lights
    state: 'off'
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.tv_auto_lights
    state: 'off'
action:
  # - service: script.auto_light_on
  #   data:
  #     entity: "group.living_room_track_lights"
  - service: script.turn_on    
    entity_id: script.living_room_theme
    data_template:
      variables:
        theme_color: "{{ states('sensor.progressive_day_theme')|replace(' ', '_') }}"