alias: 'Auto Off Kitchen'
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion_1_sensor
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'    
#   - condition: state
#     entity_id: binary_sensor.kitchen_motion_1_sensor
#     state: 'off'
#     for:
#       minutes: 3
action:
  - service: script.auto_light_off
    data:
      entity: group.kitchen_lights