alias: 'Auto Off Living Room'
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'off'
    for:
      minutes: 40
  - platform: state
    entity_id: binary_sensor.living_room_occupancy
    to: 'off'
condition:
  - condition: state
    entity_id: group.living_room_lights
    state: 'on'
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.living_room_motion
        state: 'off'
      - condition: state
        entity_id: binary_sensor.living_room_occupancy
        state: 'off'
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: template
    value_template: '{{ states("media_player.living_room_cr2") == "idle" }}'
action:
  - service: script.auto_light_off
    data:
      entity: light.office_c_1
  - service: script.auto_light_off
    data:
      entity: light.lx_office_1
  # - service: script.auto_light_off
  #   data:
  #     entity: light.office_b_1