alias: 'Auto Lights Office'
trigger:
  platform: state
  entity_id: binary_sensor.office_motion_1
  from: 'off'
  to: 'on'
condition:
  - condition: state
    entity_id: light.office_c_1
    state: 'off'
  - condition: state
    entity_id: light.office_l_1
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.office_c_1
    data:
      brightness: 250
      color_temp: 350
  - service: light.turn_on
    entity_id: light.office_l_1
    data:
      brightness: 250
      color_temp: 350