alias: 'Auto Off Bedroom'
trigger:
  platform: state
  entity_id: binary_sensor.bedroom_motion_1_sensor
  from: 'on'
  to: 'off'
  # for:
  #   minutes: 45
condition:
  # condition: or
  # conditions:
  #   - condition: state
  #     entity_id: binary_sensor.upstairs_motion
  #     state: 'on'
  - condition: state
    entity_id: binary_sensor.bedroom_motion_1_sensor
    state: 'off'
    for:
      minutes: 20
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
action:
  - service: light.turn_off
    entity_id: light.bedroom_c_1
  - service: light.turn_off
    entity_id: light.bedroom_l_1  