alias: 'Auto Lights Office'
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.office_occupancy
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.house_auto_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'    
action:
  - service: scene.turn_on
    data_template:
      entity_id:
        scene.office_{{ states('sensor.progressive_day_theme')|replace(' ', '_') | lower }}