alias: "Auto Away"
trigger:
  - platform: state
    entity_id: group.nick
    to: 'not_home'
  - platform: state
    entity_id: input_boolean.guests_present
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.guests_present
    state: 'off'  
  - condition: state
    entity_id: group.nick
    state: 'not_home'
action:
  - service: light.turn_off
    entity_id: group.inside_lights
  - service: climate.set_away_mode
    entity_id: climate.main_floor
    data:
      away_mode: 'on'
  - service: script.turn_on
    entity_id: script.turn_off_living_room
  - service: switch.turn_off
    entity_id: switch.laundry_mat
#  - service: media_player.turn_off
#    entity_id: media_player.tv
  # - service: notify.pushbullet
  #   data:
  #     title: Smell Ya Later
  #     message: I'll make sure everythings off for ya!