alias: "Bedroom Dash Turn Off Alarm"
trigger:
  platform: state
  entity_id: sensor.bedroom_dash
  to: '2'
action:
  - service: light.turn_on
    entity_id: light.bedroom_c_2
    data:      
      flash: short
  - service: media_player.turn_off    
    data:
      entity_id: media_player.bedroom_dot