alias: 'Bedroom Flic Double Click'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: bedroom
      click_type: double
action:
  - service: light.turn_off
    data:
      entity_id: group.bedroom_lights