alias: "Bedroom Dash Toggle Light 2 and 3"
trigger:
  platform: state
  entity_id: sensor.bedroom_dash
  to: '3'
action:
  - service: light.turn_on
    entity_id: light.bed_strip_1
    data:      
      flash: short
  - service: light.toggle
    entity_id: light.bedroom_c_1
  - service: light.toggle
    entity_id: light.bedroom_c_2
  