alias: "Climate Lights Off"
trigger:
  platform: numeric_state
  entity_id: sensor.dark_sky_cloud_coverage
  below: 18
condition:  
  - condition: state
    entity_id: input_boolean.auto_lights_climate
    state: 'On'
  - condition: state
    entity_id: input_boolean.state_climate_scene_active
    state: 'On'
  - condition: sun
    before: sunset
    before_offset: "-1:15:00"
  - condition: state
    entity_id: group.nick
    state: home
  - condition: time
    after: '11:00:00'
action:
  service: light.turn_off
  entity_id: group.sun_room
  data:
    transition: 60