alias: 'Coffee Table Flic 2 Single Click'
trigger:
  platform: state
  entity_id: sensor.coffee_table_flic_2
  to: '1'
action:
  - service: light.turn_on
    entity_id: group.living_room_lights
  - service: script.turn_on
    entity_id: script.living_room_theme
    data_template:
      variables:
        theme_color: "{{ states('input_select.house_theme')|replace(' ', '_') }}"