alias: 'Coffee Table Flic 1 Double Click'
trigger:
  platform: state
  entity_id: sensor.coffee_table_flic_1
  to: '2'
action:
  - service: media_player.media_play
    data:
      entity_id: media_player.living_room_cr2