alias: 'Coffee Table Flic 1 Hold'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: coffee_table_1
      click_type: hold
action:
  - service: media_player.media_stop
    data:
      entity_id: media_player.living_room_cr2