alias: 'Coffee Table Flic 1 Single Click'
trigger:
  platform: state
  entity_id: sensor.coffee_table_flic_1
  to: '1'
action:
  - service: media_player.media_pause
    data:
      entity_id: media_player.living_room_cr2