alias: 'Coffee Table Flic 2 Single Click'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: coffee_table_2
      click_type: single
  # platform: state
  # entity_id: sensor.coffee_table_flic_2
  # to: '1'
action:
  - service: scene.turn_on
    entity_id: scene.living_room_dim