alias: 'Coffee Table Flic 2 Hold'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: coffee_table_2
      click_type: hold
action:
  - service: scene.turn_on
    entity_id: scene.living_room_late_night