alias: 'Coffee Table Flic 1 Double Click'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: coffee_table_1
      click_type: double
action:
  - service: script.turn_on
    entity_id: script.entertainment_turn_on