alias: 'Coffee Table Flic 1 Single Click'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: coffee_table_1
      click_type: single
action:
  - service: media_player.media_pause
    data:
      entity_id: media_player.living_room_cr2