alias: 'Coffee Table Flic 1 Hold'
trigger:
  platform: state
  entity_id: sensor.coffee_table_flic_1
  to: '3'
action:
  - service: media_player.media_stop
    data:
      entity_id: media_player.living_room_cr2