alias: "Eth Daily"
trigger:
  platform: time
  at: '09:30:00'
action:
 - service: notify.pushbullet
   data_template:
    title: "Crypto Daily Update!"
    message: "BTC: ${{states.sensor.bitcoin.state}}. ETH: ${{ states.sensor.ethereum.state }}. ZCash: ${{ states.sensor.zcash.state }}. "