alias: "Eth Crash"
trigger:
  platform: numeric_state
  entity_id: sensor.ethereum
  below: 200
action:
 - service: notify.pushbullet
   data_template:
     title: "ETH Crashed!"
     message: "ETH Price Change: ${{ states.sensor.ethereum.state }}. Time to buy!"