alias: "Guests Detection"
trigger:
  - platform: state
    entity_id: group.occupancy
    to: 'on'
  - platform: state
    entity_id: binary_sensor.motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.media_active
    to: 'on'
    for:
      seconds: 30
condition:
  - condition: state
    entity_id: input_boolean.guests_present
    state: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.guests_present