alias: "Guests Detection"
trigger:
  - platform: state
    entity_id: group.occupancy
    to: 'on'
  - platform: state
    entity_id: group.motion
    to: 'on'
  - platform: numeric_state
    entity_id: group.motion_plus
    above: 0
  - platform: state
    entity_id: media_player.tv
    to: 'playing'
    for:
      seconds: 30
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.guests_present
  - delay:
      minutes: 14
  - service: input_boolean.turn_off
    entity_id: input_boolean.guests_present