alias: "Guests Auto Off"
trigger:
  # - platform: state
  #   entity_id: group.occupancy
  #   to: 'off'
  - platform: state
    entity_id: binary_sensor.motion
    to: 'off'
  - platform: state
    entity_id: binary_sensor.media_active
    to: 'off'
    for:
      minutes: 20
condition:
  # - condition: state
  #   entity_id: group.occupancy
  #   state: 'off'
  - condition: state
    entity_id: binary_sensor.motion
    state: 'off'
  - condition: state
    entity_id: binary_sensor.media_active
    state: 'off'
    for:
      minutes: 20
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.guests_present