alias: "House Themer"
hide_entity: False
trigger:
  - platform: state
    entity_id: input_select.house_theme
action:
  - service: script.turn_on
    entity_id: script.accents_theme
    data_template:
      variables:
        theme_color: "{{ states('input_select.house_theme')|replace(' ', '_') }}"
  - service: script.turn_on
    entity_id: script.living_room_theme
    data_template:
      variables:
        theme_color: "{{ states('input_select.house_theme')|replace(' ', '_') }}"
  - service: script.turn_on
    entity_id: script.kitchen_theme
    data_template:
      variables:
        theme_color: "{{ states('input_select.house_theme')|replace(' ', '_') }}"
  - service: script.turn_on
    entity_id: script.office_theme
    data_template:
      variables:
        theme_color: "{{ states('input_select.house_theme')|replace(' ', '_') }}"
  - service: script.turn_on
    entity_id: script.sun_room_theme
    data_template:
      variables:
        theme_color: "{{ states('input_select.house_theme')|replace(' ', '_') }}"