alias: 'Office Override Deactivated'
trigger:
  - platform: state
    entity_id: input_boolean.office_override
    to: 'off'
action:
  - service: light.turn_on
    data:
      entity_id: group.office_lights
      flash: long