alias: 'Office Flic Double Click'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: office
      click_type: double
action:
  - service: light.turn_off
    data:
      entity_id: group.office_lights