alias: 'Office Desk Flic Hold'
trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: office_desk
      click_type: hold
action:
  - service: switch.toggle
    data:
      entity_id: switch.office_monitors