alias: 'Office Desk Flic Double'
trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: office_desk
      click_type: double
action:
  - service: input_boolean.toggle
    data:
      entity_id: input_boolean.office_override