alias: 'Office Flic Hold'
trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: office
      click_type: hold
action:
  - service: input_boolean.toggle
    data:
      entity_id: input_boolean.office_override