alias: "Plex Activity Monitor"
initial_state: false
trigger:
  - platform: state
    entity_id: sensor.deepthink
# condition:
#   - condition: state
#     entity_id: light.go_1
#     state: "on"
action:
  - service: homeassistant.turn_on
    entity_id: script.plex_activity_visualize