alias: 'Recover From Power Outage'
trigger:
  platform: state
  entity_id: group.nick
  to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
action:
 - service: light.turn_off
   entity_id: group.master_bathroom_lights
 - service: light.turn_off
   entity_id: group.basement_bathroom
 - service: light.turn_off
   entity_id: light.stairs   
 - service: light.turn_off
   entity_id: group.kitchen