alias: "Sunset"
trigger:
  platform: sun
  event: sunset
  offset: "-01:00:00"
condition:
  condition: state
  entity_id: device_tracker.nexus_6p
  state: 'home'
action:
 - service: scene.turn_on
   entity_id: scene.living_room_warm
 - service: scene.turn_on
   entity_id: scene.sun_room_warm
 - service: light.turn_on
   entity_id: group.accents