alias: "Sunset"
trigger:
  platform: sun
  event: sunset
  offset: "-01:00:00"
condition:
  condition: state
  entity_id: group.nick
  state: 'home'
action:
 - service: light.turn_on
   entity_id: group.living_room_lights
 - service: light.turn_on
   entity_id: group.sun_room_lights
 - service: light.turn_on
   entity_id: group.accents
 - service: script.turn_on
   entity_id: script.progressive_theme