alias: "Tv Auto Brighten"
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_media_active
    to: 'off'
    for:
      seconds: 30
  - platform: state
    entity_id: binary_sensor.bedroom_media_active
    to: 'off'
    for:
      seconds: 30  
condition:
  - condition: state
    entity_id: input_boolean.tv_auto_lights
    state: 'on'
action:
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% set fullNameParts = trigger.entity_id.split('.') %}
        {% set nameParts = fullNameParts[1].split('_') %}
        {% set scriptName = 'brighten_' + nameParts[0] %}
        {% if(nameParts[1] == 'room') %}
          {% set scriptName = scriptName + '_room' %}
        {% endif %}
        script.{{ scriptName }}
  # - service: notify.notify_slack
  #   data_template:
  #     title: "title stuff"
  #     message: >-
  #       brightening




# alias: "Tv Auto Bright"
# trigger:
#   - platform: state
#     entity_id: binary_sensor.living_room_media_active
#     to: 'off'
#     for:
#       seconds: 30
#   # - platform: state
#   #   entity_id: media_player.living_room_cr2
#   #   to: 'idle'
#   #   for:
#   #     seconds: 30
# condition:
#   - condition: state
#     entity_id: input_boolean.tv_auto_lights
#     state: 'on'
#   - condition: state
#     entity_id: binary_sensor.living_room_media_active
#     state: 'off'
#   # - condition: state
#   #   entity_id: media_player.living_room_cr2
#   #   state: 'idle'
#   # - condition: state
#   #   entity_id: media_player.vizio_tv
#   #   state: 'idle'
# action:
#   - service: script.turn_on
#     entity_id: script.group_brightness
#     data_template:
#       variables:
#         brightness: "{{ states('input_number.constant_brightness_bright') }}"
#         group: "living_room_shallow_accents"
#   - delay: 
#       seconds: 1
#   - service: script.turn_on
#     entity_id: script.group_brightness
#     data_template:
#       variables:
#         brightness: "{{ states('input_number.constant_brightness_bright') }}"
#         group: "living_room_deep_accents"
#   - delay: 
#       seconds: 1
#   - service: script.turn_on
#     entity_id: script.group_brightness
#     data_template:
#       variables:
#         brightness: "{{ states('input_number.constant_brightness_bright') }}"
#         group: "living_room_base"
#   - delay: 
#       seconds: 1
#   - service: light.turn_on
#     entity_id: light.aurora
#     data:
#       transition: 10
#       brightness: 140