alias: "Tv Auto Late Bright"
trigger:
  - platform: state
    entity_id: media_player.tv
    to: 'idle'
    for:
      seconds: 30
condition:
  - condition: state
    entity_id: input_boolean.tv_auto_lights
    state: 'on'
  - condition: time
    after: '23:20:00'
action:
  - service: scene.turn_on
    entity_id: scene.living_room_late_bright