alias: "Tv Auto Dim"
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_media_active
    to: 'on'
    for:
      seconds: 30
  - platform: state
    entity_id: binary_sensor.bedroom_media_active
    to: 'on'
    for:
      seconds: 30
condition:
  - condition: state
    entity_id: input_boolean.tv_auto_lights
    state: 'on'
action:
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% set fullNameParts = trigger.entity_id.split('.') %}
        {% set nameParts = fullNameParts[1].split('_') %}
        {% set scriptName = 'dim_' + nameParts[0] %}
        {% if(nameParts[1] == 'room') %}
          {% set scriptName = scriptName + '_room' %}
        {% endif %}
        script.{{ scriptName }}
  # - service: notify.notify_slack
  #   data_template:
  #     title: "title stuff"
  #     message: 'triggered'