alias: "Tv Auto Bright"
trigger:
  - platform: state
    entity_id: media_player.tv
    to: 'idle'
    for:
      seconds: 30
  - platform: state
    entity_id: media_player.living_room_cr2
    to: 'idle'
    for:
      seconds: 30
condition:
  - condition: state
    entity_id: input_boolean.tv_auto_lights
    state: 'on'
action:
  - service: scene.turn_on
    data_template:
      entity_id: > 
        {% if is_state("sensor.time_of_day", "Late Night") %}
          scene.living_room_late_bright
        {% else %}
          scene.living_room_bright
        {% endif %}
  - service: input_boolean.turn_off
    entity_id: input_boolean.is_living_room_dim